# -*- coding: utf-8 -*-
"""register_china.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAugXbETKMbZJ8wrNLnvWoxgQRT_R81I
"""

import pandas as pd
import os
import re

DATA_DIR = '/content/sample_data'

dfs = []

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set a professional style
sns.set(style="whitegrid")
plt.rcParams.update({
    "figure.figsize": (6, 4),
    "font.size": 10,
    "lines.linewidth": 1.5,
    "axes.labelsize": 10,
    "axes.titlesize": 12,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "legend.frameon": False,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "grid.linestyle": "--",
    "text.usetex": False,
})

# pip install python-docx pandas

# all_rows = []

# for file in os.listdir(DATA_DIR):
#     if not file.endswith(".docx"):
#         continue
#     if "备案" not in file:
#         continue

#     file_path = os.path.join(DATA_DIR, file)
#     doc = Document(file_path)

#     # ---- extract month ----
#     match = re.search(r"(\d{4})年(\d{1,2})月", file)
#     if match:
#         year, month = match.groups()
#         month_value = f"{year}-{int(month)}"
#     else:
#         month_value = None

#     # ---- service type ----
#     if "合成" in file:
#         service_type = "generative ai"
#     elif "信息服务" in file:
#         service_type = "algorithmic service"
#     else:
#         service_type = None
#     # ---- read tables ----
#     for table in doc.tables:
#         rows = table.rows

#         # skip first 2 rows
#         for row in rows[2:]:
#             cells = [cell.text.strip() for cell in row.cells]

#             # skip empty rows
#             if all(c == "" for c in cells):
#                 continue

#             row_dict = {
#                 f"col_{i+1}": value for i, value in enumerate(cells)
#             }

#             # add metadata columns
#             row_dict["month"] = month_value
#             row_dict["service_type"] = service_type
#             row_dict["source_file"] = file

#             all_rows.append(row_dict)

# # ---- concat into DataFrame ----
# final_df = pd.DataFrame(all_rows)

# print(final_df.head())

# df = final_df.drop(columns=["col_7"], errors="ignore")

# df = df.rename(columns={
#     "col_2": "model_name",
#     "col_3": "category",
#     "col_4": "entity",
#     "col_5": "product_name",
#     "col_6": "intended_purpose"
# })

# # ---- reset index as first column ----
# df = df.reset_index(drop=True)
# df.insert(0, "id", df.index + 1)

# df = df.drop(columns=["id"], errors="ignore")
# df = df.drop(columns=["col_1"], errors="ignore")

# # df = df.drop(columns=["col_1"], errors="ignore")
# df = df.drop(columns=["col_8"], errors="ignore")
# df = df.drop(columns=["col_9"], errors="ignore")

# df.to_csv("data_china.csv", index=False)

df= pd.read_csv("data_china.csv")

df.shape

import matplotlib.pyplot as plt
# line graph to compare monthly growth of regisration

counts = (
    df
    .groupby(["month", "service_type"])["model_name"]
    .count()
    .unstack()
    .fillna(0)
    .sort_index()
)

category_counts = (
    df
    .groupby(["month", "category"])["model_name"]
    .count()
    .unstack()
    .fillna(0)
    .sort_index()
)

category_translation = {
    "个性化推送类": "Personalized Recommendation",
    "信息检索类": "Information Retrieval",
    "内容过滤类": "Content Filtering",
    "排序精选类": "Ranking / Selection (Sorting)",
    "服务技术支持者": "Generative AI – Technical Support",
    "服务提供者": "Generative AI – Service Provider",
    "检索过滤类": "Retrieval & Filtering",  # placeholder translation
    "生成合成类": "Generative / Synthetic",
    "调度决策类": "Scheduling-Related Decision-Making"
}

category_counts = category_counts.rename(columns=category_translation)

# Now category_counts has clean English column names
category_counts.head()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Reset index and convert to long format for Seaborn
category_counts_long = category_counts.reset_index().melt(
    id_vars='month',
    value_vars=category_counts.columns,
    var_name='Category',
    value_name='Count'
)

# Convert 'month' to datetime to ensure chronological order
category_counts_long['month'] = pd.to_datetime(category_counts_long['month'], format='%Y-%m')

# Set Seaborn style
sns.set_style("darkgrid")
plt.figure(figsize=(14, 7))

# Line plot with markers
sns.lineplot(
    data=category_counts_long,
    x='month',
    y='Count',
    hue='Category',
    marker='o'
)

plt.xlabel("Month", fontsize=12)
plt.ylabel("Count of Registration", fontsize=12)
plt.title("Registered Algorithm Categories Over Time", fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Category', fontsize=16, loc='upper left')
plt.tight_layout()
plt.show()

category_totals = category_counts.sum()

category_totals

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 14))
plt.pie(
    category_totals,
    labels=category_totals.index,
    autopct=lambda p: f'{p:.1f}%',  # keeps one decimal
    startangle=140,
    colors=sns.color_palette("pastel"),
    textprops={'fontsize': 16}      # increases label font size
)
plt.title("Overall Distribution of Algorithm Categories", fontsize=20)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Your data
data = {
    "category": [
        "Personalized Recommendation",
        "Information Retrieval",
        "Content Filtering",
        "Ranking / Selection (Sorting)",
        "Generative AI – Technical Support",
        "Generative AI – Service Provider",
        "Retrieval & Filtering",
        "Generative / Synthetic",
        "Scheduling-Related Decision-Making"
    ],
    "value": [348, 100, 23, 67, 1167, 3919, 101, 10, 87]
}

category_totals = pd.Series(data['value'], index=data['category'])

# Normalize font size between 10 and 25 based on slice size
min_font = 6
max_font = 18
values = category_totals.values
font_sizes = min_font + (values - values.min()) / (values.max() - values.min()) * (max_font - min_font)

plt.figure(figsize=(14, 14))
wedges, texts, autotexts = plt.pie(
    category_totals,
    labels=category_totals.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=sns.color_palette("pastel"),
    wedgeprops={'edgecolor': 'white'}
)

# Apply dynamic font size to labels and percentages
for i, text in enumerate(texts):
    text.set_fontsize(font_sizes[i])
for i, autotext in enumerate(autotexts):
    autotext.set_fontsize(font_sizes[i])

plt.title("Overall Distribution of Algorithm Categories", fontsize=20)
plt.tight_layout()
plt.show()

# Select rows where category is one of the three specified
selected_categories = df[df['category'].isin(['生成合成类'])]

# Show the first few rows
selected_categories.head(20)

pinduoduo_rows = df[df['product_name'] == '得物（APP）']

# Show the filtered rows
pinduoduo_rows.head()

total_entities = df['entity'].nunique()
print(f"There are {total_entities} unique entities in the dataset.")

entity_counts = df['entity'].value_counts()

# Count how many entities have exactly 1 registration
entities_with_one_registration = (entity_counts == 1).sum()

print(f"{entities_with_one_registration} entities have only 1 registration.")

entities_with_one_registration = (entity_counts == 2).sum()

print(f"{entities_with_one_registration} entities have only 2 registration.")

# Count how many entities have exactly 1 registration
entities_with_one_registration = (entity_counts == 3).sum()

print(f"{entities_with_one_registration} entities have only 3 registration.")

entities_with_one_registration = (entity_counts == 4).sum()

print(f"{entities_with_one_registration} entities have only 4 registration.")

165/3787

# Count number of rows per entity
entity_counts = df['entity'].value_counts().sort_values(ascending=False)
print(entity_counts[:6])

# Top 10 entities
top10_entity = entity_counts.head(10)

# Total registrations (all rows)
total_registrations = len(df)

# Registrations for top 10 entities
top10_count = top10_entity.sum()

# Percentage of total
percentage_top10 = top10_count / total_registrations * 100

print(f"Top 10 entities account for {top10_count} registrations,")
print(f"which is {percentage_top10:.2f}% of all registrations.")

# Count number of registrations per entity
entity_counts = df['entity'].value_counts()

# Count how many entities have exactly 1 registration
num_entities_one_registration = (entity_counts == 1).sum()

# Total number of entities
total_entities = len(entity_counts)

# Percentage
percentage_one_registration = num_entities_one_registration / total_entities * 100

print(f"Number of entities with only 1 registration: {num_entities_one_registration}")
print(f"Total number of entities: {total_entities}")
print(f"Percentage of entities with only 1 registration: {percentage_one_registration:.2f}%")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.pyplot as plt
import seaborn as sns

# # Count how many registrations each entity has
# entity_counts = df['entity'].value_counts()

# # Count how many entities have 1, 2, 3, ... registrations
# registration_distribution = entity_counts.value_counts().sort_index()

# # Plot
# sns.set_style("whitegrid")
# plt.figure(figsize=(12, 6))
# sns.barplot(x=registration_distribution.index, y=registration_distribution.values, palette="viridis")

# plt.xlabel("Number of Registrations per Entity")
# plt.ylabel("Number of Entities")
# plt.title("Distribution of Entities by Number of Registrations")
# plt.xticks(rotation=0)
# plt.tight_layout()
# plt.show()

# Example mapping from Chinese names to English
name_mapping = {
    "深圳市腾讯计算机系统有限公司": "Tencent",
    "北京抖音信息服务有限公司": "ByteDance",
    "北京百度网讯科技有限公司": "Baidu Netcom",
    "上海商汤智能科技有限公司": "SenseTime",
    "北京红棉小冰科技有限公司": "Xiaobing (Microsoft Research Asia before)",
    "深圳力维智联技术有限公司": "Shenzhen Liwei"
}

# Replace Chinese names with English names in the DataFrame
df['entity_english'] = df['entity'].replace(name_mapping)

# Count how many registrations each entity has (English names)
entity_counts = df['entity_english'].value_counts()

# Count how many entities have 1, 2, 3, ... registrations
registration_distribution = entity_counts.value_counts().sort_index()

# Colors for all bars
colors = ['skyblue'] * len(registration_distribution)

plt.figure(figsize=(12, 6))
bars = plt.bar(registration_distribution.index, registration_distribution.values,
               color=colors, edgecolor='none', linewidth=2, width=0.8)  # default no edge

plt.xlabel("Number of Registrations per Entity")
plt.ylabel("Number of Entities")
plt.title("Distribution of Entities by Number of Registrations")
plt.xticks(rotation=0)

# Annotate and add edge only for bars with more than 15 registrations
for i, num_entities in enumerate(registration_distribution.values):
    num_registrations = registration_distribution.index[i]

    if num_registrations > 15:
        # Get all entities with this number of registrations
        entities_to_annotate = entity_counts[entity_counts == num_registrations].index.tolist()
        annotation_text = ", ".join(entities_to_annotate)

        # Annotate the bar
        plt.text(num_registrations, num_entities + 0.5, annotation_text,
                 ha='center', va='bottom', fontsize=9, rotation=10)

        # Add black edge to the bar
        bars[i].set_edgecolor('black')
        bars[i].set_linewidth(2)

plt.tight_layout()
plt.show()

deepseek = df[df['entity'].str.contains("深度求索", na=False)]

deepseek

### deepseek was released 20 January 2025

tencent = df[df['entity'].str.contains("腾讯", na=False)]

tencent

products_per_entity = tencent.groupby('entity')['product_name'].nunique().sort_values(ascending=False)
print("Number of unique products per Tencent entity:")
print(products_per_entity)

service_counts = tencent['service_type'].value_counts()
total_rows = len(tencent)
service_percentage = service_counts / total_rows * 100
print("\nPercentage of each service type for Tencent:")
print(service_percentage)

category_counts = tencent['category'].value_counts()
total_rows = len(tencent)
category_percentage = category_counts / total_rows * 100
print("\nPercentage of each category type for Tencent:")
print(category_percentage)

# Convert 'month' column to datetime
tencent['month'] = pd.to_datetime(tencent['month'], format='%Y-%m', errors='coerce')

# Count number of registrations per month
registrations_by_month = tencent.groupby(tencent['month'].dt.to_period('M')).size()
print("\nTencent registrations per month:")
print(registrations_by_month)

aug_2022 = tencent[tencent['month'] == pd.to_datetime('2022-08')]
aug_2022
# jan_2023 = tencent[tencent['month'] == pd.to_datetime('2023-01')]

product_counts = df['product_name'].value_counts().sort_values(ascending=False)
print(product_counts)

dingding = df[df['product_name'].str.contains("钉钉", na=False)]

dingding

prodcut_rows = df[df['product_name'] == '--']
prodcut_rows.shape

support_rows = df[df['category'] == '服务技术支持者']
prodcut_rows.shape