# -*- coding: utf-8 -*-
"""UK_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKtPS9fRV7SZMB-wXadSpoCT-cGAAUYl
"""

# import requests
# from bs4 import BeautifulSoup
# import pandas as pd

# # URL of the page to scrape
# url = "https://www.gov.uk/algorithmic-transparency-records"  # Replace with the actual page URL
# base_url = "https://www.gov.uk"  # Base URL for relative links

# # Fetch the page
# response = requests.get(url)
# soup = BeautifulSoup(response.text, "html.parser")

# # Get the first document item
# item = soup.select_one("#js-results .gem-c-document-list__item")

# # Extract title and link
# title_tag = item.select_one(".gem-c-document-list__item-title a")
# title = title_tag.get_text(strip=True)
# link = base_url+title_tag['href']

# # Extract description
# description_tag = item.select_one(".gem-c-document-list__item-description")
# description = description_tag.get_text(strip=True) if description_tag else ""

# # Extract metadata
# metadata_tags = item.select(".gem-c-document-list__attribute")
# metadata_dict = {}
# for tag in metadata_tags:
#     if ":" in tag.text:
#         key, value = tag.text.split(":", 1)
#         metadata_dict[key.strip()] = value.strip()
#     else:
#         metadata_dict[tag.text.strip()] = ""

# # Prepare single-row dictionary with fixed columns
# row = {
#     "Title": title,
#     "Description": description,
#     "Organisation": metadata_dict.get("Organisation", ""),
#     "Organisation type": metadata_dict.get("Organisation type", ""),
#     "Function": metadata_dict.get("Function", ""),
#     "Phase": metadata_dict.get("Phase", ""),
#     "Region": metadata_dict.get("Region", ""),
#     "ATRS version": metadata_dict.get("ATRS version", ""),
#     "Date published": metadata_dict.get("Date published", ""),
#     "Link": link
# }

# # Convert to DataFrame to view
# df = pd.DataFrame([row])
# print(df)

# urls = [
#     "https://www.gov.uk/algorithmic-transparency-records",
#     "https://www.gov.uk/algorithmic-transparency-records?page=2"
# ]

# base_url = "https://www.gov.uk"


# data = []  # Initialize once, outside the loop

# for url in urls:
#     response = requests.get(url)
#     soup = BeautifulSoup(response.text, "html.parser")

#     # Find all document list items
#     items = soup.select("#js-results .gem-c-document-list__item")

#     for item in items:
#         # Extract title and link
#         title_tag = item.select_one(".gem-c-document-list__item-title a")
#         title = title_tag.get_text(strip=True)
#         link = base_url + title_tag['href']

#         # Extract description
#         description_tag = item.select_one(".gem-c-document-list__item-description")
#         description = description_tag.get_text(strip=True) if description_tag else ""

#         # Extract metadata
#         metadata_tags = item.select(".gem-c-document-list__attribute")
#         metadata_dict = {}
#         for tag in metadata_tags:
#             if ":" in tag.text:
#                 key, value = tag.text.split(":", 1)
#                 metadata_dict[key.strip()] = value.strip()
#             else:
#                 metadata_dict[tag.text.strip()] = ""

#         # Build row with fixed columns
#         row = {
#             "Title": title,
#             "Description": description,
#             "Organisation": metadata_dict.get("Organisation", ""),
#             "Organisation type": metadata_dict.get("Organisation type", ""),
#             "Function": metadata_dict.get("Function", ""),
#             "Phase": metadata_dict.get("Phase", ""),
#             "Region": metadata_dict.get("Region", ""),
#             "ATRS version": metadata_dict.get("ATRS version", ""),
#             "Date published": metadata_dict.get("Date published", ""),
#             "Link": link
#         }

#         data.append(row)

# # Convert to DataFrame
# df = pd.DataFrame(data)

# df.to_csv("govuk_algorithmic_transparency.csv", index=False)

import pandas as pd
import os
import re

DATA_DIR = '/content/sample_data'

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set a professional style
sns.set(style="whitegrid")
plt.rcParams.update({
    "figure.figsize": (6, 4),
    "font.size": 10,
    "lines.linewidth": 1.5,
    "axes.labelsize": 10,
    "axes.titlesize": 12,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "legend.frameon": False,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "grid.linestyle": "--",
    "text.usetex": False,
})

df= pd.read_csv("govuk_algorithmic_transparency.csv")

df

import matplotlib.pyplot as plt
import seaborn as sns

columns_to_plot = [
    "Organisation",
    "Organisation type",
    "Function",
    "Phase",
    "Region",
    "ATRS version"
]

for col in columns_to_plot:
    plt.figure(figsize=(12, 6))
    sns.countplot(data=df, y=col, order=df[col].value_counts().index)
    plt.title(f"Distribution of {col}")
    plt.xlabel("Count")
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Set global theme and parameters
sns.set(style="whitegrid")
plt.rcParams.update({
    "figure.figsize": (6, 4),
    "font.size": 10,
    "lines.linewidth": 1.5,
    "axes.labelsize": 10,
    "axes.titlesize": 12,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "legend.frameon": False,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "grid.linestyle": "--",
    "text.usetex": False,
})

# Columns to plot
columns_to_plot = [
    "Organisation",
    "Organisation type",
    "Function",
    "Phase",
    "Region",
    "ATRS version"
]

# Color palette
palette = sns.color_palette("Set2")  # soft, pastel-like colors

for col in columns_to_plot:
    plt.figure(figsize=(8, 5))  # slightly bigger for readability

    ax = sns.countplot(
        data=df,
        y=col,
        order=df[col].value_counts().index,
        palette=palette
    )

    # Title and labels
    ax.set_title(f"Distribution of {col}", weight='bold')
    ax.set_xlabel("Count")
    ax.set_ylabel(col)

    # Add value labels
    for p in ax.patches:
        width = p.get_width()
        ax.text(width + 0.2, p.get_y() + p.get_height() / 3,
                f'{int(width)}', va='center')

    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Set global theme and parameters
sns.set(style="whitegrid")
plt.rcParams.update({
    "figure.figsize": (6, 4),
    "font.size": 10,
    "lines.linewidth": 1.5,
    "axes.labelsize": 10,
    "axes.titlesize": 12,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "legend.frameon": False,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "grid.linestyle": "--",
    "text.usetex": False,
})

# Columns to plot
columns_to_plot = [
    "Organisation"
]

# Color palette
palette = sns.color_palette("Set2")  # soft, pastel-like colors

for col in columns_to_plot:
    plt.figure(figsize=(14, 7))  # slightly bigger for readability

    ax = sns.countplot(
        data=df,
        y=col,
        order=df[col].value_counts().index,
        palette=palette
    )

    # Title and labels
    ax.set_title(f"Distribution of {col}", weight='bold')
    ax.set_xlabel("Count")
    ax.set_ylabel(col)

    # Add value labels
    for p in ax.patches:
        width = p.get_width()
        ax.text(width + 0.2, p.get_y() + p.get_height() / 2,
                f'{int(width)}', va='center')

    plt.tight_layout()
    plt.show()

df['Year'] = pd.to_datetime(df['Date published'], errors='coerce').dt.year

# Now you can check
print(df[['Date published', 'Year']].head())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Year', palette='viridis', order=sorted(df['Year'].dropna().unique()))
plt.title("Number of entries by Year")
plt.xlabel("Year")
plt.ylabel("Count")
plt.show()

df_filtered = df[df['Year'].isin([2022, 2025])]

# Group by Organisation and collect the years they have entries in
dept_years = df_filtered.groupby('Organisation')['Year'].unique()

# Select organisations that have both 2022 and 2025
departments_both_years = dept_years[dept_years.apply(lambda x: set([2022, 2025]).issubset(set(x)))]

# Show the result
print("Departments publishing in both 2022 and 2025:")
print(departments_both_years.index.tolist())

import requests
from bs4 import BeautifulSoup

# Example URL
url = "https://www.gov.uk/algorithmic-transparency-records/dwp-urgent-journal-messages"

# Fetch the page
response = requests.get(url)
response.raise_for_status()

# Parse the HTML
soup = BeautifulSoup(response.text, "html.parser")

# Find the target div(s)
target_divs = soup.find_all("div", class_="govuk-grid-column-two-thirds")

# Extract text content
text = "\n\n".join(div.get_text(strip=True, separator="\n") for div in target_divs)

print(text)

forecasting_link = soup.find("a", class_="govuk-link govuk-link--inverse", string="Forecasting")
forecasting_text = forecasting_link.get_text(strip=True) if forecasting_link else None

# --- Find the <dd> following <dt>Task: ---
task_dt = soup.find("dt", class_="gem-c-metadata__term", string="Task:")
event_prediction_dd = None

if task_dt:
    # Find the next <dd> sibling (could be separated by whitespace/newlines)
    event_prediction_dd = task_dt.find_next_sibling("dd", class_="gem-c-metadata__definition")

event_prediction_text = event_prediction_dd.get_text(strip=True) if event_prediction_dd else None

# --- Output ---
print("capability:", forecasting_text)
print("Task:", event_prediction_text)



# import csv
# import requests
# from bs4 import BeautifulSoup

# input_csv = "/content/govuk_algorithmic_transparency.csv"
# output_csv = "govuk_algorithmic_transparency_output.csv"  # new CSV with extra columns

# def extract_data(url):
#     """Scrape Forecasting, Task, and main text from a GOV.UK page."""
#     try:
#         response = requests.get(url, timeout=15)
#         response.raise_for_status()
#         soup = BeautifulSoup(response.text, "html.parser")

#         # --- 1️⃣ Forecasting capability link ---
#         forecasting_link = soup.find("a", class_="govuk-link govuk-link--inverse", string="Forecasting")
#         forecasting_text = forecasting_link.get_text(strip=True) if forecasting_link else ""

#         # --- 2️⃣ Task (dd following dt: Task:) ---
#         task_dt = soup.find("dt", class_="gem-c-metadata__term", string="Task:")
#         task_dd = task_dt.find_next_sibling("dd", class_="gem-c-metadata__definition") if task_dt else None
#         event_prediction_text = task_dd.get_text(strip=True) if task_dd else ""

#         # --- 3️⃣ Main text inside <div class="govuk-grid-column-two-thirds"> ---
#         main_divs = soup.find_all("div", class_="govuk-grid-column-two-thirds")
#         full_text = "\n\n".join(div.get_text(strip=True, separator="\n") for div in main_divs)

#         return forecasting_text, event_prediction_text, full_text

#     except Exception as e:
#         print(f"Error scraping {url}: {e}")
#         return "", "", ""


# # --- Read input CSV and write output CSV ---
# with open(input_csv, newline='', encoding="utf-8") as infile, \
#      open(output_csv, "w", newline='', encoding="utf-8") as outfile:

#     reader = csv.DictReader(infile)
#     fieldnames = reader.fieldnames + ["Capability", "Task", "Full text"]
#     writer = csv.DictWriter(outfile, fieldnames=fieldnames)
#     writer.writeheader()

#     for row in reader:
#         url = row.get("Link", "").strip()
#         if url:
#             capability, task, full_text = extract_data(url)
#             row["Capability"] = capability
#             row["Task"] = task
#             row["Full text"] = full_text
#             print(f"✅ {row['Title']} -> Capability: {capability}, Task: {task}")
#         else:
#             row["Capability"] = ""
#             row["Task"] = ""
#             row["Full text"] = ""

#         writer.writerow(row)

# print(f"\n✅ Done! Saved results to {output_csv}")

# input_csv = "/content/govuk_algorithmic_transparency.csv"
# output_csv = "govuk_algorithmic_transparency_output.csv"

# def extract_data(url):
#     """
#     Scrape Forecasting, Task, and main text from a GOV.UK page.
#     Raises exceptions if the request fails.
#     """
#     response = requests.get(url, timeout=15)
#     response.raise_for_status()  # raises HTTPError if response not 200
#     soup = BeautifulSoup(response.text, "html.parser")

#     # --- Forecasting capability ---
#     forecasting_link = soup.find(
#         "a", class_="govuk-link govuk-link--inverse", string="Forecasting"
#     )
#     forecasting_text = forecasting_link.get_text(strip=True) if forecasting_link else ""

#     # --- Task ---
#     task_dt = soup.find("dt", class_="gem-c-metadata__term", string="Task:")
#     task_dd = task_dt.find_next_sibling("dd", class_="gem-c-metadata__definition") if task_dt else None
#     task_text = task_dd.get_text(strip=True) if task_dd else ""

#     # --- Full text ---
#     main_divs = soup.find_all("div", class_="govuk-grid-column-two-thirds")
#     full_text = "\n\n".join(div.get_text(strip=True, separator="\n") for div in main_divs)

#     return forecasting_text, task_text, full_text


# # --- Load input CSV ---
# with open(input_csv, newline="", encoding="utf-8") as infile:
#     reader = list(csv.DictReader(infile))
#     input_rows = len(reader)
#     print(f"Input CSV rows: {input_rows}")

# # --- Write output CSV ---
# with open(output_csv, "w", newline="", encoding="utf-8") as outfile:
#     # Keep original columns + new ones
#     fieldnames = list(reader[0].keys()) + ["Capability", "Task", "Full text"]
#     writer = csv.DictWriter(outfile, fieldnames=fieldnames)
#     writer.writeheader()

#     for row in tqdm(reader, desc="Processing rows", total=input_rows):
#         url = row.get("Link", "").strip()
#         try:
#             if url:
#                 capability, task, full_text = extract_data(url)


#                 if not task:
#                     task = "Not specified"


#                 if not capability:
#                     capability = "Not available"
#             else:
#                 capability, task, full_text = "Not available", "Not specified", "Not available"

#         except Exception as e:
#             print(f"❌ Failed for URL: {url} -> {e}")
#             capability, task, full_text = "", "Not specified", "Not available"

#         # Add extracted data to the row
#         row["Capability"] = capability
#         row["Task"] = task
#         row["Full text"] = full_text

#         # Always write the row
#         writer.writerow(row)



import pandas as pd
import matplotlib.pyplot as plt

# Read your output CSV
df = pd.read_csv("govuk_algorithmic_transparency_output.csv")

# Count occurrences of each Task value
task_counts = df["Task"].value_counts().dropna()

# Create pie chart
plt.figure(figsize=(14, 14))
plt.pie(
    task_counts,
    labels=task_counts.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={"edgecolor": "white"}
)

plt.title("Distribution of Tasks (from GOV.UK ATRS pages)")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Count occurrences of each Task value
task_counts = df["Task"].value_counts(dropna=True)

# Calculate percentage of each task
task_percent = task_counts / task_counts.sum() * 100

# Combine tasks with less than 2% into "Others"
task_counts_combined = task_counts.copy()
task_counts_combined[task_percent < 2] = 0
others_count = task_counts[task_percent < 2].sum()

# Keep only tasks >= 2% and add "Others"
task_counts_final = task_counts_combined[task_counts_combined > 0]
if others_count > 0:
    task_counts_final["Others"] = others_count

# Plot pie chart
plt.figure(figsize=(14, 14))
plt.pie(
    task_counts_final,
    labels=task_counts_final.index,
    autopct='%1.1f%%',
    startangle=90,
    colors=sns.color_palette("pastel"),
    wedgeprops={"edgecolor": "white"},
    textprops={'fontsize': 14}
)
plt.title("Distribution of Tasks (from GOV.UK ATRS pages)")
plt.tight_layout()
plt.show()

df.shape

import pandas as pd
import matplotlib.pyplot as plt


# Drop empty or missing Task values
df = df.dropna(subset=["Task"])
df = df[df["Task"].str.strip() != ""]

# Count the tasks
task_counts = df["Task"].value_counts()

# Keep top 20 tasks and combine the rest as "Other"
top_20 = task_counts.nlargest(20)
top_20

import re


def clean_full_text(text):
    if not isinstance(text, str):
        return text
    # Use regex to cut off text after "Updates to this page" or "Published"
    pattern = r"(Updates to this page).*"
    return re.sub(pattern, "", text, flags=re.IGNORECASE | re.DOTALL).strip()

# Apply the function to the Full text column
df["Full text"] = df["Full text"].apply(clean_full_text)

print(df["Full text"].iloc[0])

from wordcloud import WordCloud
import matplotlib.pyplot as plt
from collections import Counter



# Function to extract text after "5.2 - Risks and mitigations"
def extract_after_risks(text):
    if not isinstance(text, str):
        return ""
    marker = "5.2 - Risks and mitigations"
    pos = text.find(marker)
    if pos != -1:
        return text[pos + len(marker):].strip()
    else:
        return ""  # marker not found

# Apply the function to Full text column
df["Risks_text"] = df["Full text"].apply(extract_after_risks)

# Combine all extracted text
all_risks_text = " ".join(df["Risks_text"].dropna().astype(str))

# Clean text: remove punctuation, numbers, lowercase
all_risks_clean = re.sub(r'[^A-Za-z\s]', '', all_risks_text).lower()

# --- Generate Word Cloud ---
wordcloud = WordCloud(
    width=800, height=400, background_color='white', colormap='tab10', max_words=100
).generate(all_risks_clean)

plt.figure(figsize=(15, 7))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud of Risks (after 5.2 - Risks and mitigations)", fontsize=16)
plt.show()

words = all_risks_clean.split()
word_counts = Counter(words)
top_words = word_counts.most_common(100)

print("Top 20 words mentioned in risks:")
for word, count in top_words:
    print(f"{word}: {count}")

top_100_words = set([word for word, count in word_counts.most_common(100)])

filtered_words = [word for word in words if word not in top_100_words]
filtered_text = " ".join(filtered_words)

# Generate word cloud
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white',
    colormap='tab10',
    max_words=100
).generate(filtered_text)

plt.figure(figsize=(15, 7))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud of Risks (after removing top 100 words)", fontsize=16)
plt.show()

import google.generativeai as genai

genai.configure(api_key="AIzaSyCGqKsDEXDVVRFdN2P5ZamdBZLBwJ79F58")

model_name = "gemini-2.5-pro"  # Choose the model you have access to

def extract_risks_section(text):
    if not isinstance(text, str):
        return ""
    marker = "5.2 - Risks and mitigations"
    pos = text.find(marker)
    if pos != -1:
        return text[pos + len(marker):].strip()
    else:
        return ""

df.info()

import json
import pandas as pd # Assuming you use pandas for 'df'
from google import genai
from google.genai import types

# Initialize client (Use an environment variable for a real project)
client = genai.Client(api_key="AIzaSyCGqKsDEXDVVRFdN2P5ZamdBZLBwJ79F58") # API Key should be kept secret




def extract_risks_with_gemini(section_text):
    if not section_text:
        return []

    # Improved prompt for clarity and strict JSON adherence
    prompt = prompt = f"""
Extract all risks mentioned in the following text.

For each risk, provide:
- "risk": a short, concise name for the risk
- "description": a short description of what the risk involves. If no description is provided, use "N/A".
- "mitigation": any mitigation, control, or action mentioned. If none is provided, use "N/A".

Return the output strictly as a JSON array of objects. DO NOT include any explanatory text or markdown formatting (e.g., ```json).

Do not skip any risks if information about them is given, even if only mitigation or description is mentioned.

Example:
Input Text:
"The risk of incorrectly flagging journal messages is partially mitigated by: • Collecting feedback to improve the model. • Appropriate training for users of the urgent flags • Any missed messages will be replied to using business as usual processes."

Expected Output:
{{
    "risk": "Incorrect Flagging of Journal Messages",
    "description": "N/A",
    "mitigation": "Collecting feedback to improve the model; Appropriate training for users of the urgent flags; Any missed messages will be replied to using business as usual processes"
}}

Text:
{section_text}
"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                # CRITICAL FIX: Forces the model to only output the JSON structure
                response_mime_type="application/json"
            )
        )
        text_output = response.text
        # Safely load the guaranteed JSON output
        risks_json = json.loads(text_output)
        return risks_json
    except json.JSONDecodeError as e:
        print(f"Error: Model did not return valid JSON. Output was: {text_output}")
        print("JSON Decode Error:", e)
        return []
    except Exception as e:
        print("Error extracting risks:", e)
        return []

from tqdm import tqdm

risks_list = []

# Loop with progress bar
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Processing rows"):
    section_text = extract_risks_section(row["Full text"])
    risks_json = extract_risks_with_gemini(section_text)
    risks_list.append(json.dumps(risks_json))  # store as JSON string

# Assign results to DataFrame
df["Risks_JSON"] = risks_list

df.to_csv("output_with_risks.csv", index=False)

df["Risks_JSON"].iloc[0]

def extract_json_columns(json_str):
    items = json.loads(json_str)  # parse JSON
    risk = ", ".join([i["risk"] for i in items])
    description = ", ".join([i["description"] for i in items])
    mitigation = ", ".join([i["mitigation"] for i in items])
    return pd.Series([risk, description, mitigation])

# Apply the function to each row
df[["risk", "description", "mitigation"]] = df["Risks_JSON"].apply(extract_json_columns)

print(df[["risk", "description", "mitigation"]])

df["risk"].head(5)

all_risk = df['risk'].str.split(",").explode().unique().tolist()
all_risks

df[df['risk'].isna() | (df['risk'] == '')]